<a href="https://colab.research.google.com/github/javohuz/Data_Science_and_AI/blob/main/%20NumPy/%2308_Where.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# where shart operatoralari
  - `np.where(condition, t,f) `  = > condition = shart, agar shartni True bulsa t urnida turgan elemen , agar False bulsa f urnida turgan element qiymati berilgan array yaratiladi ,
  - `natija = np.where(arr>0 , 1,-1 )` masalan shundey


In [ ]:
import numpy as np

In [ ]:
t = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
f = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
print(t,f)
np.where()

[1.1 1.2 1.3 1.4 1.5] [2.1 2.2 2.3 2.4 2.5]


In [ ]:
# cond
cond = np.array([True, False, False, True ,True])

In [ ]:
# where t turgan joy True , f turgan joy False qiymat qaytaradi
resalt = np.where(cond , t,f)
resalt

array([1.1, 2.2, 2.3, 1.4, 1.5])

In [ ]:
arr = np.random.randn(5,5)
print(arr)


[[ 2.62781163e-01  2.15635382e+00  1.47811752e+00  1.19743555e+00
  -3.67771778e-01]
 [-2.04344401e-01 -5.02250347e-01  1.36900142e+00 -1.02222335e+00
   1.31086331e+00]
 [ 5.96948992e-01 -1.22291008e+00 -6.98559143e-01 -1.38729939e+00
   5.17590488e-01]
 [-1.34596219e-01  2.05245808e+00 -7.46330566e-01 -2.06237388e+00
  -1.99287751e-03]
 [-1.23545964e+00  2.69388528e-01 -4.13174526e-01  9.47919292e-02
  -1.12139410e+00]]


In [ ]:
natija = np.where(arr>0 , 1,-1 )
natija

array([[ 1,  1,  1,  1, -1],
       [-1, -1,  1, -1,  1],
       [ 1, -1, -1, -1,  1],
       [-1,  1, -1, -1, -1],
       [-1,  1, -1,  1, -1]])