<a href="https://colab.research.google.com/github/javohuz/Data_Science_and_AI/blob/main/NumPy/%2301-Arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# #01 Lesson: Working with NumPy Library
   

# Why need Numpy ?


NumPy => python kutubhunalaridan biri c tillarida yozilgan listdan ancha tezroq , vectorlashgan va shunga uhshash boshqa qulayliklari borligi sababli foyldalaniladi
 - Asosan ARRAYlar uchun

In [33]:
import numpy as np

In [34]:
my_list=list(range(100000)) # python list : normal
my_array=np.array(range(100000)) # numpy array : vectorized
print(type(my_array))

<class 'numpy.ndarray'>


Spending time for x*2 that python list  

In [35]:
%time for _ in range(10) :[ x*2 for x in my_list]

CPU times: user 68.8 ms, sys: 0 ns, total: 68.8 ms
Wall time: 74.9 ms


Spending time for x*2 that numpy array or vectorized

In [36]:
%time for _ in range(10) : 2*my_array

CPU times: user 1.11 ms, sys: 3 µs, total: 1.11 ms
Wall time: 1.12 ms


In [37]:
66.5/3.92

16.964285714285715

Numpy array (vectorized) speed is faster then python list (normal)

# Array

***Array yaratish***

---

1. ` np.array(list)`  => oddiy listdan iborat erray
2. `np.zeros(shape=(q,u) or (q,u) )`  => barcha elementlari o dan iborat arrey shape qator va ustular
3. `np.ones(shape=(q,u) or (q,u) )` => barcha elementlari 1 dan iborat array
4. `np.arange(start, stop , step)` => looks like range

In [22]:
list1=[1,4,6,2,6,2]
list2=[2,6,6,3,5,3] # simple list

arr1=np.array(list1)  # array

arr2=np.array([list1 , list2]) # array arr2

print(len(list1))

6


In [32]:
arr3=np.zeros(shape=(2,5)) # faqat 0
arr4=np.ones( (2,5) ) # faqat 1

arr5=np.arange(2,15,2) # like range

print(arr3)
print(arr4)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


**Array uzunligi**

---


  - `np.ndim` => len(array)
  - `np.shape` => qator va ustunlar soni (q , U)
  - `np.size` => erray ichidagi barcha elemenlar

In [21]:
a=np.ndim(arr1)  # len => ndim uzunligi
b=np.ndim(arr2)
print(a,b)

1 2


In [25]:
np.shape(arr2) # qatorlar va ustular soni
np.size(arr2) # barcha elemetlar soni

12