<a href="https://colab.research.google.com/github/javohuz/Data_Science_and_AI/blob/main/NumPy/%2304_Boolean.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Boolean
  Boolean true yoki falsa javobibi qaytardi va shu yordamida amallar bajarsih imkonini beradi
  
- ` | `=> tayoqcha or degan manoni dagan manoni beradi
- `mask = (names == "Javohir") | (names=="Hasan")`

In [1]:
import numpy as np

In [5]:
# Ismlar
names = np.array(['Hasan', 'Husan', 'Javohir', 'Elyor', 'Hasan', 'Javohir', 'Elyor'])
names

array(['Hasan', 'Husan', 'Javohir', 'Elyor', 'Hasan', 'Javohir', 'Elyor'],
      dtype='<U7')

In [10]:
data = np.random.randn(7,4)
data

array([[-0.89306565, -0.26519357,  0.34452198, -0.30573802],
       [ 0.44465102, -0.18587366,  0.32404763,  0.88294087],
       [ 1.77208425,  0.30990513,  0.13784293,  0.84759258],
       [ 0.62465026,  0.52100214, -0.01415131,  0.58204237],
       [ 0.88926426, -0.56830036,  0.14630704, -0.11333459],
       [ 0.76058154,  1.39571633,  0.59338272, -0.74794875],
       [-1.29810694, -2.02491485, -0.54634017,  0.01097459]])

In [6]:
names == "Javohir"

array([False, False,  True, False, False,  True, False])

In [12]:
data[names == "Javohir"]

array([[ 1.77208425,  0.30990513,  0.13784293,  0.84759258],
       [ 0.76058154,  1.39571633,  0.59338272, -0.74794875]])

agar tepadagi random orqali berilgan arrayni malum bir qatoridagi sonlar kerak bulsa pastda

In [13]:
data[names == "Javohir" , :2 ]

array([[1.77208425, 0.30990513],
       [0.76058154, 1.39571633]])

Aksincha bitta qiymatdan boshqa qiymatlar kerak bulsa

In [15]:
data[names != "Javohir"]
data[~(names == "Javohir")] # ikalasinign ham vazifasi birxil

array([[-0.89306565, -0.26519357,  0.34452198, -0.30573802],
       [ 0.44465102, -0.18587366,  0.32404763,  0.88294087],
       [ 0.62465026,  0.52100214, -0.01415131,  0.58204237],
       [ 0.88926426, -0.56830036,  0.14630704, -0.11333459],
       [-1.29810694, -2.02491485, -0.54634017,  0.01097459]])

Birdaniga ikkta isimnig data dagi malumotlarini olsish uchun avval uzgaruvchi yaratib olamiz

In [17]:
mask = (names == "Javohir") | (names=="Hasan")
mask

array([ True, False,  True, False,  True,  True, False])

In [18]:
data[mask]

array([[-0.89306565, -0.26519357,  0.34452198, -0.30573802],
       [ 1.77208425,  0.30990513,  0.13784293,  0.84759258],
       [ 0.88926426, -0.56830036,  0.14630704, -0.11333459],
       [ 0.76058154,  1.39571633,  0.59338272, -0.74794875]])

Data ishidagi malum qiymatlarni uzgartirmoqchi bulsak misol uchun hama manfiy sonlarni =0 qilaylik

In [19]:
data

array([[-0.89306565, -0.26519357,  0.34452198, -0.30573802],
       [ 0.44465102, -0.18587366,  0.32404763,  0.88294087],
       [ 1.77208425,  0.30990513,  0.13784293,  0.84759258],
       [ 0.62465026,  0.52100214, -0.01415131,  0.58204237],
       [ 0.88926426, -0.56830036,  0.14630704, -0.11333459],
       [ 0.76058154,  1.39571633,  0.59338272, -0.74794875],
       [-1.29810694, -2.02491485, -0.54634017,  0.01097459]])

In [21]:
data[data<0]=0
data

array([[0.        , 0.        , 0.34452198, 0.        ],
       [0.44465102, 0.        , 0.32404763, 0.88294087],
       [1.77208425, 0.30990513, 0.13784293, 0.84759258],
       [0.62465026, 0.52100214, 0.        , 0.58204237],
       [0.88926426, 0.        , 0.14630704, 0.        ],
       [0.76058154, 1.39571633, 0.59338272, 0.        ],
       [0.        , 0.        , 0.        , 0.01097459]])

Yoki shunga ushash amallar bajarib uzimizga kerak li kurinishga olib kelsak buldi har bir elementini  2 ga kupaytramiz

In [22]:
data[:]=data*2
data

array([[0.        , 0.        , 0.68904397, 0.        ],
       [0.88930203, 0.        , 0.64809526, 1.76588174],
       [3.54416849, 0.61981025, 0.27568586, 1.69518516],
       [1.24930052, 1.04200427, 0.        , 1.16408475],
       [1.77852852, 0.        , 0.29261407, 0.        ],
       [1.52116309, 2.79143266, 1.18676543, 0.        ],
       [0.        , 0.        , 0.        , 0.02194918]])