<a href="https://colab.research.google.com/github/javohuz/Data_Science_and_AI/blob/main/NumPy/%2310_Sorting_and_Filter.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Sorting tartiblash
  - `np.sort(arr)` tugri tartiblash
  - `-np.sort(-arr)` = > teskari tartiblash
  - `np.unique(arr)` erray ichidagi birxil elementlarni olib sorting qiladi
  - `np.in1d(arr1, arr2)`  = > arr1 arrayda arr2 arrayidagi bilan bir xil bulgan elemenlarga True qiymat qaytaradi
  - `np.setdiff1d(arr1 , arr2) ` = arr1 arrayda arr2 arrayidagi bilan bir xil bulmagan elemenlarga True qiymat qaytaradi

In [1]:
import numpy as np


In [4]:
arr = np.random.randn(2,5)
arr

array([[-0.16224926,  1.41650351,  1.06335314, -1.1955368 , -0.28444031],
       [ 1.88113583,  0.5036022 , -0.36601295, -0.79414868, -2.16368695]])

In [8]:
sorted = np.sort(arr)
sorted01 = np.sort(arr)
print(sorted , sorted01 )

[[-1.1955368  -0.28444031 -0.16224926  1.06335314  1.41650351]
 [-2.16368695 -0.79414868 -0.36601295  0.5036022   1.88113583]] [[-1.1955368  -0.28444031 -0.16224926  1.06335314  1.41650351]
 [-2.16368695 -0.79414868 -0.36601295  0.5036022   1.88113583]]


- axis = 0 ustun
- axis = 1 qator

In [13]:
axis0sort = np.sort(arr , axis = 0)
axis1sort = np.sort(arr , axis = 1)
print(axis0sort )
print(axis1sort)

[[-2.16368695 -0.79414868 -0.36601295  0.5036022   1.41650351]
 [-1.1955368  -0.28444031 -0.16224926  1.06335314  1.88113583]]
[[-1.1955368  -0.28444031 -0.16224926  1.06335314  1.41650351]
 [-2.16368695 -0.79414868 -0.36601295  0.5036022   1.88113583]]


Teskari tartiblash

In [14]:
arr1 = np.arange(6)
arr1

array([0, 1, 2, 3, 4, 5])

In [15]:
teskarisort = -np.sort(-arr1)
teskarisort

array([5, 4, 3, 2, 1, 0])

`unique`

In [24]:
names = np.array(['Sarvar', 'Abdurahmon', 'Hasan',  'Temur', 'Sarvar', 'Temur'])
ints = np.array([3, 3, 3, 2, 2, 1, 1, 4, 4])
uniqued = np.unique(names)
uniqued1 = np.unique(ints)
print(uniqued , uniqued1 )

['Abdurahmon' 'Hasan' 'Sarvar' 'Temur'] [1 2 3 4]


`in1d`

In [30]:
arr1 = np.array([6, 0, 0, 3, 2, 5, 6])
arr2 = np.array([0, 2, 3])

in1d12 = np.in1d(arr1, arr2 )
arr12 = arr1[in1d12]
print(np.unique(arr12))


[0 2 3]


`setdiff1d`

In [31]:
arr1 = np.array([6, 0, 0, 3, 2, 5, 6])
arr2 = np.array([0, 2, 3])

in1d12 = np.setdiff1d(arr1, arr2 )
arr12 = arr1[in1d12]
print(np.unique(arr12))

[5 6]


# Filtirlash

In [18]:
arr2 = np.array([12,22,23,24])
arr3 = [True , False , False , True]

filterarr2 = arr2[arr3]
filterarr2

array([12, 24])

In [21]:
arr4 = np.random.randn(6)
filterarr4 = arr4>0
print(arr4)
filtered = arr4[filterarr4]

print(filterarr4)
print(filtered)


[-0.16844767  0.07721194  3.29099407 -0.48314976 -0.39067562 -1.05547434]
[False  True  True False False False]
[0.07721194 3.29099407]


In [23]:
arr5 = np.arange(6)
filterarr5 = arr5 %2==0
print(arr5)
filtered = arr5[filterarr5]

print(filterarr5)
print(filtered)

[0 1 2 3 4 5]
[ True False  True False  True False]
[0 2 4]
